# Generated by Django 3.0.7 on 2020-06-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_food_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='time',
        ),
    ]
